### ISSUE TITLE
Bug:  Year wraps in auto generated readme

### ISSUE THREAD

**Issue by zoidy** [ualibraries/LD_Cool_P#180]
**Describe the bug**
Seems like when generating the readme, sometimes the year wraps to the next line. See C. H. readme files. Might be related to #142 not sure. 

**Reproduction Steps**
Generate the readme file from one of C. H's deposits

**Outputted Messages**
N/A

**Version information**
- LD_Cool-P version: 0.17.4 f409453

*Expected behavior*
Year does not break unless the line is too long. See readme files of other recent deposits.

*Screenshots*
![image](https://user-images.githubusercontent.com/7082025/111395361-ed940e00-8679-11eb-9b05-ec862bad9575.png)

*Additional context*
N/A

**Comment by astrochun** [comment]
This is a separate issue from #142 and it's a known minor bug introduced from missing a possible edge case from early development on the README.txt generation and `jinja2` templating. The intent is to provide a four-line block of the preferred citation to so that it is readable from a text editor. That block is intended to be:
Line 1 - author list, year
Line 2 - Title
Line 3 - Source (i.e., University of Arizona Research Data Repository)
Line 4 - Type of data, DOI link

`figshare` API only provides it as a single line block and the content of each of them is not always available. For example, this is the only place that the author list is provided as a semi-colon separated list. You could parse it from the `authors` metadata but it's quite painful. The simplest solution I came up with is to split with periods before the start of a new sentence (i.e., ". "). At that time we didn't have any deposits with the last author having an abbreviation middle name. This is why it's being split before the (YYYY).

The issue is present in this code snippet: https://github.com/ualibraries/LD_Cool_P/blob/0b9e24a310bb7f8b445b91416e160d9b727ffd45/ldcoolp/curation/inspection/readme/__init__.py#L217-L224

This has been an issue I wanted to fix but it's so small that it's minor. I can see if there's a better way.

**Comment by zoidy** [comment]
Agreed, It's low priority.

**Comment by astrochun** [comment]
> Agreed, It's low priority.

I have a possible idea for fixing it, so let me experiment and let you know if this will work. If I can fix it, I'll just deploy it today as a hotfix.

**Comment by astrochun** [comment]
> Note that for long authors, the `et al.` introduce a similar problem (e.g., Haffert's [deposit](https://doi.org/10.25422/azu.data.12857885.v1)). I think the best way to address this is with `regex`.
> 
> Will need to combine solution from two stackoverflow suggestion:
> 
> 1. https://stackoverflow.com/questions/46498544/ignore-part-of-match-in-re-split
> 2. https://stackoverflow.com/questions/30933216/split-by-regex-without-resulting-empty-strings-in-python/30933281

The following solution I think is more robust and has a cleaner fix to combine Item type and DOI in the same link:
```python
END_SENT = re.compile('((?<=[.!?])|(?<=\.\":)) +(?=[A-Z,0-9])')
citation_list = list(filter(None, END_SENT.split(single_str_citation.replace('):', ').'))))
```

For the following:
"Haffert, Sebastiaan; Harris, Robert J.; Zanutta, Alessio; Pike, Fraser A.; Bianco, Andrea; Redaelli, Eduardo; et al. (2020): Data for "Diffraction-limited integral-field spectroscopy for extreme adaptive-optics systems with the Multi-Core fiber-fed Integral-Field Unit". University of Arizona Research Data Repository. Dataset. https://doi.org/10.25422/azu.data.12857885.v1"

We get:
```python
citation_list = list(filter(None, END_SENT.split(haffert_str.replace('):', ').'))))                                                                      

['Haffert, Sebastiaan; Harris, Robert J.; Zanutta, Alessio; Pike, Fraser A.; Bianco, Andrea; Redaelli, Eduardo; et al. (2020).',
 'Data for "Diffraction-limited integral-field spectroscopy for extreme adaptive-optics systems with the Multi-Core fiber-fed Integral-Field Unit".',
 'University of Arizona Research Data Repository.',
 'Dataset. https://doi.org/10.25422/azu.data.12857885.v1']
```

And for:
"Haffert, Sebastiaan; Harris, Robert J. (2020): Data for "Diffraction-limited integral-field spectroscopy for extreme adaptive-optics systems with the Multi-Core fiber-fed Integral-Field Unit". University of Arizona Research Data Repository. Dataset. https://doi.org/10.25422/azu.data.12857885.v1"

We get:

```python
citation2_list = list(filter(None, END_SENT.split(haffert2_str.replace('):', ').'))))                                                                       

['Haffert, Sebastiaan; Harris, Robert J. (2020).',
 'Data for "Diffraction-limited integral-field spectroscopy for extreme adaptive-optics systems with the Multi-Core fiber-fed Integral-Field Unit".',
 'University of Arizona Research Data Repository.',
 'Dataset. https://doi.org/10.25422/azu.data.12857885.v1']
```
